[workspace]

members = [
    "makepad",
    "makepad/wasm", 
    "examples/audio_example",
    "examples/bare_example", 
    "examples/bare_example/wasm",
    "examples/hello_world",
    "examples/widget_example",
    "examples/cmdline_example",
    "examples/cmykw_example",
    "examples/webgl_example_wasm",
    "tools/webserver",
    "tools/brotli_test",
    "builder"
]

[profile.release]
#lto=true
 
